
# Podfile for Eylo

platform :ios, '15.0'

# Ignore warnings from some pods
inhibit_all_warnings!

target 'Eylo' do
  use_frameworks!

  # Pods for Eylo
  pod 'KeychainAccess'
  
  target 'EyloShare' do
    inherit! :search_paths
    # Pods for testing
  end
end
